import { MenuItem } from '@/types';

export const menuData: MenuItem[] = [
  // Portal Admin Menu
  {
    id: 'portal-admin-users',
    label: 'Users',
    href: '/portal-admin/users',
    icon: 'Users',
    roles: ['portal_admin'],
    children: [
      {
        id: 'portal-admin-users-list',
        label: 'Users List',
        href: '/portal-admin/users',
        icon: 'List',
        roles: ['portal_admin'],
      },
      {
        id: 'portal-admin-create-user',
        label: 'Create User',
        href: '/portal-admin/users/create',
        icon: 'UserPlus',
        roles: ['portal_admin'],
      },
    ],
  },
  {
    id: 'portal-admin-enumerators',
    label: 'Enumerators',
    href: '/portal-admin/enumerators',
    icon: 'Users',
    roles: ['portal_admin'],
    children: [
      {
        id: 'portal-admin-enumerators-list',
        label: 'Enumerator List',
        href: '/portal-admin/enumerators',
        icon: 'List',
        roles: ['portal_admin'],
      },
      {
        id: 'portal-admin-create-enumerator',
        label: 'Create Enumerator',
        href: '/portal-admin/enumerators/create',
        icon: 'UserPlus',
        roles: ['portal_admin'],
      },
    ],
  },
  {
    id: 'portal-admin-cron-jobs',
    label: 'CRON Job Manager',
    href: '/portal-admin/cron-jobs',
    icon: 'Clock',
    roles: ['portal_admin'],
  },
  {
    id: 'portal-admin-downloads',
    label: 'Downloads',
    href: '/portal-admin/downloads',
    icon: 'Download',
    roles: ['portal_admin'],
  },

  // Super Admin Menu
  {
    id: 'dashboard',
    label: 'Dashboard',
    href: '/super-admin/dashboard',
    icon: 'Home',
    roles: ['super_admin'],
  },
  {
    id: 'user-management',
    label: 'User Management',
    href: '/super-admin/users',
    icon: 'Users',
    roles: ['super_admin'],
  },
  {
    id: 'role-management',
    label: 'Role Management',
    href: '/super-admin/roles',
    icon: 'Shield',
    roles: ['super_admin'],
  },
  {
    id: 'feature-management',
    label: 'Feature Management',
    href: '/super-admin/features',
    icon: 'Settings',
    roles: ['super_admin'],
  },
  {
    id: 'page-management',
    label: 'Page Management',
    href: '/super-admin/pages',
    icon: 'FileText',
    roles: ['super_admin'],
  },
  {
    id: 'system-information',
    label: 'System Information',
    href: '/super-admin/system',
    icon: 'Server',
    roles: ['super_admin'],
  },
  {
    id: 'components',
    label: 'Components',
    href: '/dashboard/components',
    icon: 'Sliders',
    roles: ['super_admin'],
    children: [
      {
        id: 'select-demo',
        label: 'Select Components',
        href: '/dashboard/components/select-demo',
        icon: 'CheckCircle',
        roles: ['super_admin'],
      },
      {
        id: 'form-validation-demo',
        label: 'Form Validation',
        href: '/dashboard/components/form-validation-demo',
        icon: 'FileText',
        roles: ['super_admin'],
      },
      {
        id: 'form-builder-demo',
        label: 'Form Builder',
        href: '/dashboard/components/form-builder-demo',
        icon: 'Settings',
        roles: ['super_admin'],
      },
      {
        id: 'modal-demo',
        label: 'Modal Components',
        href: '/dashboard/components/modal-demo',
        icon: 'FileText',
        roles: ['super_admin'],
      },
      {
        id: 'form-components-demo',
        label: 'Form Components',
        href: '/dashboard/components/form-components-demo',
        icon: 'Settings',
        roles: ['super_admin'],
      },
      {
        id: 'ui-components-demo',
        label: 'UI Components',
        href: '/dashboard/components/ui-components-demo',
        icon: 'Sliders',
        roles: ['super_admin'],
      },
      {
        id: 'medium-components-demo',
        label: 'Medium Components',
        href: '/dashboard/components/medium-components-demo',
        icon: 'BarChart3',
        roles: ['super_admin'],
      },
      {
        id: 'utility-components-demo',
        label: 'Utility Components',
        href: '/dashboard/components/utility-components-demo',
        icon: 'Settings',
        roles: ['super_admin'],
      },
      {
        id: 'advanced-components-demo',
        label: 'Advanced Components',
        href: '/dashboard/components/advanced-components-demo',
        icon: 'Settings',
        roles: ['super_admin'],
      },
    ],
  },

  // ============================================
  // CAPI SYSTEM MENUS
  // ============================================

  // CAPI Project Progress Monitoring (PPM) Menu
  {
    id: 'capi-ppm-overview',
    label: 'Overview',
    href: '/capi/ppm/overview/fieldwork-progress',
    icon: 'BarChart3',
    roles: ['ppm'],
    system: 'capi',
    children: [
      {
        id: 'capi-ppm-fieldwork-progress',
        label: 'Fieldwork Progress',
        href: '/capi/ppm/overview/fieldwork-progress',
        icon: 'BarChart3',
        roles: ['ppm'],
        system: 'capi',
      },
      {
        id: 'capi-ppm-interview-log',
        label: 'Interview Log',
        href: '/capi/ppm/overview/interview-log',
        icon: 'FileText',
        roles: ['ppm'],
        system: 'capi',
      },
    ],
  },
  {
    id: 'capi-ppm-master',
    label: 'Master',
    href: '/capi/ppm/master/aclist',
    icon: 'Database',
    roles: ['ppm'],
    system: 'capi',
    children: [
      {
        id: 'capi-ppm-ac-list',
        label: 'AC List',
        href: '/capi/ppm/master/aclist',
        icon: 'Users',
        roles: ['ppm'],
        system: 'capi',
      },
      {
        id: 'capi-ppm-team-registration',
        label: 'Team Registration',
        href: '/capi/ppm/master/team-registration',
        icon: 'Users',
        roles: ['ppm'],
        system: 'capi',
      },
      // {
      //   id: 'capi-ppm-project-setting',
      //   label: 'Project Setting',
      //   href: '/capi/ppm/master/project-setting',
      //   icon: 'Settings',
      //   roles: ['ppm'],
      //   system: 'capi',
      // },
    ],
  },
  {
    id: 'capi-ppm-interviewer',
    label: 'Interviewer',
    href: '/capi/ppm/interviewer/master',
    icon: 'Users',
    roles: ['ppm'],
    system: 'capi',
    children: [
      {
        id: 'capi-ppm-interviewer-master',
        label: 'Master',
        href: '/capi/ppm/interviewer/master',
        icon: 'Users',
        roles: ['ppm'],
        system: 'capi',
      },
      {
        id: 'capi-ppm-interviewer-assigned',
        label: 'Assigned',
        href: '/capi/ppm/interviewer/assigned',
        icon: 'Users',
        roles: ['ppm'],
        system: 'capi',
      },
    ],
  },
  {
    id: 'capi-ppm-progress-report',
    label: 'Progress Report',
    href: '/capi/ppm/progress-report',
    icon: 'BarChart3',
    roles: ['ppm'],
    system: 'capi',
  },
  {
    id: 'capi-ppm-rejection-report',
    label: 'Rejection Report',
    href: '/capi/ppm/rejection-report',
    icon: 'XCircle',
    roles: ['ppm'],
    system: 'capi',
  },
  // {
  //   id: 'capi-ppm-gps-map',
  //   label: 'GPS Map',
  //   href: '/capi/ppm/gps-map',
  //   icon: 'Map',
  //   roles: ['ppm'],
  //   system: 'capi',
  // },
  // {
  //   id: 'capi-ppm-demographic',
  //   label: 'Demographic %',
  //   href: '/capi/ppm/demographic',
  //   icon: 'Users',
  //   roles: ['ppm'],
  //   system: 'capi',
  // },
  // {
  //   id: 'capi-ppm-uploads',
  //   label: 'Uploads',
  //   href: '/capi/ppm/uploads/change-status',
  //   icon: 'Upload',
  //   roles: ['ppm'],
  //   system: 'capi',
  //   children: [
  //     {
  //       id: 'capi-ppm-change-status',
  //       label: 'Change Status',
  //       href: '/capi/ppm/uploads/change-status',
  //       icon: 'Edit',
  //       roles: ['ppm'],
  //       system: 'capi',
  //     },
  //     {
  //       id: 'capi-ppm-send-to-qc',
  //       label: 'Send to QC',
  //       href: '/capi/ppm/uploads/send-to-qc',
  //       icon: 'Send',
  //       roles: ['ppm'],
  //       system: 'capi',
  //     },
  //     {
  //       id: 'capi-ppm-weights',
  //       label: 'Weights',
  //       href: '/capi/ppm/uploads/weights',
  //       icon: 'Scale',
  //       roles: ['ppm'],
  //       system: 'capi',
  //     },
  //     {
  //       id: 'capi-ppm-cron-request',
  //       label: 'Cron Request',
  //       href: '/capi/ppm/uploads/cron-request',
  //       icon: 'Clock',
  //       roles: ['ppm'],
  //       system: 'capi',
  //     },
  //   ],
  // },
  {
    id: 'capi-ppm-master-data',
    label: 'Master Data',
    href: '/capi/ppm/master-data/master-ac',
    icon: 'Database',
    roles: ['ppm'],
    system: 'capi',
    children: [
      {
        id: 'capi-ppm-master-ac',
        label: 'Master AC',
        href: '/capi/ppm/master-data/master-ac',
        icon: 'Users',
        roles: ['ppm'],
        system: 'capi',
      },
      // {
      //   id: 'capi-ppm-master-pc',
      //   label: 'Master PC',
      //   href: '/capi/ppm/master-data/master-pc',
      //   icon: 'Users',
      //   roles: ['ppm'],
      //   system: 'capi',
      // },
      // {
      //   id: 'capi-ppm-master-district',
      //   label: 'Master District',
      //   href: '/capi/ppm/master-data/master-district',
      //   icon: 'Users',
      //   roles: ['ppm'],
      //   system: 'capi',
      // },
      // {
      //   id: 'capi-ppm-master-region',
      //   label: 'Master Region',
      //   href: '/capi/ppm/master-data/master-region',
      //   icon: 'Users',
      //   roles: ['ppm'],
      //   system: 'capi',
      // },
      // {
      //   id: 'capi-ppm-master-ac-caste',
      //   label: 'Master AC Caste',
      //   href: '/capi/ppm/master-data/master-ac-caste',
      //   icon: 'Users',
      //   roles: ['ppm'],
      //   system: 'capi',
      // },

    ],
  },
  {
    id: 'capi-ppm-ps-form',
    label: 'PS for Form',
    href: '/capi/ppm/ps-form',
    icon: 'FileText',
    roles: ['ppm'],
    system: 'capi',
  },

  // CAPI Project Progress Monitoring Team (PPMT) Menu
  {
    id: 'capi-ppmt-overview',
    label: 'Overview',
    href: '/capi/ppmt/overview/fieldwork-progress',
    icon: 'BarChart3',
    roles: ['ppmt'],
    system: 'capi',
    children: [
      {
        id: 'capi-ppmt-fieldwork-progress',
        label: 'Fieldwork Progress',
        href: '/capi/ppmt/overview/fieldwork-progress',
        icon: 'BarChart3',
        roles: ['ppmt'],
        system: 'capi',
      },
      {
        id: 'capi-ppmt-interview-log',
        label: 'Interview Log',
        href: '/capi/ppmt/overview/interview-log',
        icon: 'FileText',
        roles: ['ppmt'],
        system: 'capi',
      },
    ],
  },
  {
    id: 'capi-ppmt-interviewer',
    label: 'Interviewer',
    href: '/capi/ppmt/interviewer/master',
    icon: 'Users',
    roles: ['ppmt'],
    system: 'capi',
    children: [
      {
        id: 'capi-ppmt-interviewer-master',
        label: 'Master',
        href: '/capi/ppmt/interviewer/master',
        icon: 'Users',
        roles: ['ppmt'],
        system: 'capi',
      },
      {
        id: 'capi-ppmt-interviewer-assigned',
        label: 'Assigned',
        href: '/capi/ppmt/interviewer/assigned',
        icon: 'Users',
        roles: ['ppmt'],
        system: 'capi',
      },
    ],
  },
  {
    id: 'capi-ppmt-progress-report',
    label: 'Progress Report',
    href: '/capi/ppmt/progress-report',
    icon: 'BarChart3',
    roles: ['ppmt'],
    system: 'capi',
  },
  {
    id: 'capi-ppmt-rejection-report',
    label: 'Rejection Report',
    href: '/capi/ppmt/rejection-report',
    icon: 'XCircle',
    roles: ['ppmt'],
    system: 'capi',
  },
  // {
  //   id: 'capi-ppmt-gps-map',
  //   label: 'GPS Map',
  //   href: '/capi/ppmt/gps-map',
  //   icon: 'Map',
  //   roles: ['ppmt'],
  //   system: 'capi',
  // },
  // {
  //   id: 'capi-ppmt-demographic',
  //   label: 'Demographic %',
  //   href: '/capi/ppmt/demographic',
  //   icon: 'Users',
  //   roles: ['ppmt'],
  //   system: 'capi',
  // },

  // CAPI Data Quality Management (DQM) Menu
  {
    id: 'capi-dqm-qc-user-registration',
    label: 'QC User Registration',
    href: '/capi/dqm/qc-user-registration',
    icon: 'UserPlus',
    roles: ['dqm'],
    system: 'capi',
  },
  {
    id: 'capi-dqm-qc-team-registration',
    label: 'QC Team Registration',
    href: '/capi/dqm/qc-team-registration',
    icon: 'Users',
    roles: ['dqm'],
    system: 'capi',
  },
  // {
  //   id: 'capi-dqm-fieldwork-progress',
  //   label: 'Fieldwork Progress',
  //   href: '/capi/dqm/fieldwork-progress',
  //   icon: 'BarChart3',
  //   roles: ['dqm'],
  //   system: 'capi',
  // },
  {
    id: 'capi-dqm-progress',
    label: 'Progress',
    href: '/capi/dqm/progress/qc-user-progress',
    icon: 'BarChart3',
    roles: ['dqm'],
    system: 'capi',
    children: [
      {
        id: 'capi-dqm-qc-user-progress',
        label: 'QC User Progress',
        href: '/capi/dqm/progress/qc-user-progress',
        icon: 'BarChart3',
        roles: ['dqm'],
        system: 'capi',
      },
      {
        id: 'capi-dqm-interview-list',
        label: 'Interview List',
        href: '/capi/dqm/progress/interview-list',
        icon: 'FileText',
        roles: ['dqm'],
        system: 'capi',
      },
      // // 
      // {
      //   id: 'capi-dqm-qc-user-pending-data',
      //   label: 'QC User - Pending Data',
      //   href: '/capi/dqm/progress/qc-user-pending-data',
      //   icon: 'Clock',
      //   roles: ['dqm'],
      //   system: 'capi',
      // },
      // {
      //   id: 'capi-dqm-ac-wise-pending-data',
      //   label: 'AC Wise - Pending Data',
      //   href: '/capi/dqm/progress/ac-wise-pending-data',
      //   icon: 'MapPin',
      //   roles: ['dqm'],
      //   system: 'capi',
      // },
    ],
  },


  {
    id: 'capi-dqm-report',
    label: 'Report',
    href: '/capi/dqm/report/interview-date-wise',
    icon: 'FileText',
    roles: ['dqm'],
    system: 'capi',
    children: [

      {
        id: 'capi-dqm-telecaller-assigned-ac',
        label: 'Assigned AC',
        href: '/capi/dqm/report/telecallerassigned',
        icon: 'MapPin',
        roles: ['dqm'],
        system: 'capi',
      },
      // {
      //   id: 'capi-dqm-interview-date-wise',
      //   label: 'Interview Date Wise',
      //   href: '/capi/dqm/report/interview-date-wise',
      //   icon: 'Calendar',
      //   roles: ['dqm'],
      //   system: 'capi',
      // },
      // {
      //   id: 'capi-dqm-enumerator-wise',
      //   label: 'Enumerator Wise',
      //   href: '/capi/dqm/report/enumerator-wise',
      //   icon: 'Users',
      //   roles: ['dqm'],
      //   system: 'capi',
      // },
      {
        id: 'capi-dqm-ac-wise-report',
        label: 'AC Wise Report',
        href: '/capi/dqm/report/acwisereport',
        icon: 'MapPin',
        roles: ['dqm'],
        system: 'capi',
      },
      // {
      //   id: 'capi-dqm-assigned-ac',
      //   label: 'Assigned AC',
      //   href: '/capi/dqm/report/assigned-ac',
      //   icon: 'MapPin',
      //   roles: ['dqm'],
      //   system: 'capi',
      // },
    ],
  },
  // {
  //   id: 'capi-dqm-demographic',
  //   label: 'Demographic %',
  //   href: '/capi/dqm/demographic',
  //   icon: 'Users',
  //   roles: ['dqm'],
  //   system: 'capi',
  // },
  // {
  //   id: 'capi-dqm-gps-map',
  //   label: 'GPS Map',
  //   href: '/capi/dqm/gps-map',
  //   icon: 'Map',
  //   roles: ['dqm'],
  //   system: 'capi',
  // },
  // {
  //   id: 'capi-dqm-download',
  //   label: 'Download',
  //   href: '/capi/dqm/download/qc-data',
  //   icon: 'Download',
  //   roles: ['dqm'],
  //   system: 'capi',
  //   children: [
  //     {
  //       id: 'capi-dqm-qc-data',
  //       label: 'QC Data',
  //       href: '/capi/dqm/download/qc-data',
  //       icon: 'Download',
  //       roles: ['dqm'],
  //       system: 'capi',
  //     },
  //     {
  //       id: 'capi-dqm-update-request',
  //       label: 'Update Request',
  //       href: '/capi/dqm/download/update-request',
  //       icon: 'Edit',
  //       roles: ['dqm'],
  //       system: 'capi',
  //     },
  //   ],
  // },

  // CAPI Data Quality Management Team (DQMT) Menu
  {
    id: 'capi-dqmt-fieldwork-progress',
    label: 'Fieldwork Progress',
    href: '/capi/dqmt/fieldwork-progress',
    icon: 'BarChart3',
    roles: ['dqmt'],
    system: 'capi',
  },
  {
    id: 'capi-dqmt-qc-user-registration',
    label: 'QC User Registration',
    href: '/capi/dqmt/qc-user-registration',
    icon: 'UserPlus',
    roles: ['dqmt'],
    system: 'capi',
  },
  {
    id: 'capi-dqmt-progress',
    label: 'Progress',
    href: '/capi/dqmt/Progress/qc-user-progress',
    icon: 'BarChart3',
    roles: ['dqmt'],
    system: 'capi',
    children: [
      {
        id: 'capi-dqmt-qc-user-progress',
        label: 'QC User Progress',
        href: '/capi/dqmt/Progress/qc-user-progress',
        icon: 'BarChart3',
        roles: ['dqmt'],
        system: 'capi',
      },
      {
        id: 'capi-dqmt-interview-list',
        label: 'Interview List',
        href: '/capi/dqmt/Progress/interview-list',
        icon: 'FileText',
        roles: ['dqmt'],
        system: 'capi',
      },
      {
        id: 'capi-dqmt-qc-user-pending-data',
        label: 'QC User - Pending Data',
        href: '/capi/dqmt/Progress/qc-user-pending-data',
        icon: 'Clock',
        roles: ['dqmt'],
        system: 'capi',
      },
      {
        id: 'capi-dqmt-ac-wise-pending-data',
        label: 'AC Wise - Pending Data',
        href: '/capi/dqmt/Progress/ac-wise-pending-data',
        icon: 'MapPin',
        roles: ['dqmt'],
        system: 'capi',
      },
    ],
  },
  // {
  //   id: 'dqmt-ac-wise-pending-data',
  //   label: 'AC Wise - Pending Data',
  //   href: '/capi/dqmt/ac-wise-pending-data',
  //   icon: 'MapPin',
  //   roles: ['dqmt'],
  // },
  {
    id: 'capi-dqmt-report',
    label: 'Report',
    href: '/capi/dqmt/report/interview-date-wise',
    icon: 'FileText',
    roles: ['dqmt'],
    system: 'capi',
    children: [
      {
        id: 'capi-dqmt-interview-date-wise',
        label: 'Interview Date Wise',
        href: '/capi/dqmt/report/interview-date-wise',
        icon: 'Calendar',
        roles: ['dqmt'],
        system: 'capi',
      },
      {
        id: 'capi-dqmt-enumerator-wise',
        label: 'Enumerator Wise',
        href: '/capi/dqmt/report/enumerator-wise',
        icon: 'Users',
        roles: ['dqmt'],
        system: 'capi',
      },
      {
        id: 'capi-dqmt-ac-wise-report',
        label: 'AC Wise Report',
        href: '/capi/dqmt/report/ac-wise-report',
        icon: 'MapPin',
        roles: ['dqmt'],
        system: 'capi',
      },
      {
        id: 'capi-dqmt-assigned-ac',
        label: 'Assigned AC',
        href: '/capi/dqmt/report/assigned-ac',
        icon: 'MapPin',
        roles: ['dqmt'],
        system: 'capi',
      },
    ],
  },
  {
    id: 'capi-dqmt-demographic',
    label: 'Demographic %',
    href: '/capi/dqmt/demographic',
    icon: 'Users',
    roles: ['dqmt'],
    system: 'capi',
  },
  {
    id: 'capi-dqmt-gps-map',
    label: 'GPS Map',
    href: '/capi/dqmt/gps-map',
    icon: 'Map',
    roles: ['dqmt'],
    system: 'capi',
  },

  // CATI Data Quality Management (DQM) Menu
  {
    id: 'cati-ppm-qc-progress',
    label: 'QC Progress',
    href: '/cati/dqm/qc-progress/overall-qc-progress',
    icon: 'Users',
    roles: ['dqm'],
    system: 'cati',
    children: [
      {
        id: 'cati-ppm-qc-user-progress',
        label: 'QC User Progress',
        href: '/cati/dqm/qc-progress/qc-user-progress',
        icon: 'Users',
        roles: ['dqm'],
        system: 'cati',
      },
      {
        id: 'cati-ppm-qc-user-progress-daily',
        label: 'QC User Daily Progress',
        href: '/cati/dqm/qc-progress/qc-user-progress-daily',
        icon: 'Users',
        roles: ['dqm'],
        system: 'cati',
      },
      {
        id: 'cati-ppm-qc-ac-assigned',
        label: 'Assigned AC - QC User',
        href: '/cati/dqm/qc-progress/qc-ac-assigned',
        icon: 'TrendingUp',
        roles: ['dqm'],
        system: 'cati',
      },
      {
        id: 'cati-ppm-qc-ac-wise-progress',
        label: 'AC Wise Progress',
        href: '/cati/dqm/qc-progress/acwisereport',
        icon: 'BarChart3',
        roles: ['dqm'],
        system: 'cati',
      },
      {
        id: 'cati-ppm-interview-list',
        label: 'Interview List',
        href: '/cati/dqm/qc-progress/interview-list',
        icon: 'CheckCircle',
        roles: ['dqm'],
        system: 'cati',
      },
    ],
  },
  {
    id: 'ccati/dqm/ac-progress/ac-progress-dqm',
    label: 'Ac Progress',
    href: '/cati/dqm/ac-progress/ac-progress-dqm',
    icon: 'BarChart3',
    roles: ['dqm'],
    system: 'cati',
  },
  {
    id: 'cati-ppm-qc-data-entry-progress',
    label: 'Data Entry Progress',
    href: '/cati/dqm/data-entry-progress',
    icon: 'BarChart3',
    roles: ['dqm'],
    system: 'cati',
  },

  // CAPI Start QC Menu
  {
    id: 'capi-start-gps-qc',
    label: 'Start GPS QC',
    href: '/capi/start_qc/start-gps-qc',
    icon: 'Map',
    roles: ['start_qc'],
    system: 'capi',
  },
  {
    id: 'capi-start-audio-qc',
    label: 'Start Audio QC',
    href: '/capi/start_qc/start-audio-qc',
    icon: 'Mic',
    roles: ['start_qc'],
    system: 'capi',
  },
  {
    id: 'capi-start-re-qc',
    label: 'Start Re-QC',
    href: '/capi/start_qc/start-re-qc',
    icon: 'RefreshCw',
    roles: ['start_qc'],
    system: 'capi',
  },

  // CAPI QC Menu
  {
    id: 'capi-qc-auth',
    label: 'QC Authentication',
    href: '/capi/capi-qc/qc-auth',
    icon: 'Shield',
    roles: ['capi_qc'],
    system: 'capi',
  },
  {
    id: 'capi-audio-qc',
    label: 'Audio QC',
    href: '/capi/capi-qc/new-qc/0', // Will be updated dynamically with actual qc_id
    icon: 'Mic',
    roles: ['capi_qc'],
    system: 'capi',
    dynamic: true, // Show only when qc_user_data exists in localStorage
  },
  // {
  //   id: 'capi-gps-qc',
  //   label: 'GPS QC',
  //   href: '/capi/capi-qc/gps-qc/0', // Will be updated dynamically with actual qc_id
  //   icon: 'Map',
  //   roles: ['capi_qc'],
  //   system: 'capi',
  //   dynamic: true, // Show only when qc_user_data exists in localStorage
  // },

  // CAPI Findings Dashboard Menu
  {
    id: 'capi-fd-fieldwork-progress',
    label: 'Fieldwork Progress',
    href: '/capi/fd/fieldwork-progress',
    icon: 'BarChart3',
    roles: ['fd'],
    system: 'capi',
  },
  {
    id: 'capi-fd-fieldwork-progress-2',
    label: 'Fieldwork Progress2',
    href: '/capi/fd/fieldwork-progress2',
    icon: 'TrendingUp',
    roles: ['fd'],
    system: 'capi',
  },
  {
    id: 'demographics',
    label: 'Demographics',
    href: '/capi/fd/demographics',
    icon: 'BarChart3',
    roles: ['fd'],
    system: 'capi',
    children: [
      {
        id: 'capi-fd-demographics-basic',
        label: 'Basic Demographics',
        href: '/capi/fd/demographics/basic-demographics',
        icon: 'Users',
        roles: ['fd'],
        system: 'capi',
      },
      // {
      //   id: 'capi-fd-demographics-caste',
      //   label: 'Caste',
      //   href: '/capi/fd/demographics/caste',
      //   icon: 'Database',
      //   roles: ['fd'],
      //   system: 'capi',
      // },
    ],
  },
  // {
  //   id: 'capi-fd-progress-report',
  //   label: 'Progress Report',
  //   href: '/capi/fd/progress-report',
  //   icon: 'TrendingUp',
  //   roles: ['fd'],
  //   system: 'capi',
  // },
  {
    id: 'findings',
    label: 'Findings',
    href: '/capi/fd/findings',
    icon: 'BarChart3',
    roles: ['fd'],
    system: 'capi',
    children: [
      // {
      //   id: 'capi-fd-findings-gain-losses',
      //   label: 'Gain and Losses',
      //   href: '/capi/fd/findings/gain-and-losses',
      //   icon: 'TrendingUp',
      //   roles: ['fd'],
      //   system: 'capi',
      // },
      // {
      //   id: 'capi-fd-findings-second-choice',
      //   label: 'Second Choice',
      //   href: '/capi/fd/findings/second-choice',
      //   icon: 'Users',
      //   roles: ['fd'],
      //   system: 'capi',
      // },
      // {
      //   id: 'capi-fd-findings-vote-share',
      //   label: 'Vote Share Estimate',
      //   href: '/capi/fd/findings/vote-share-estimate',
      //   icon: 'BarChart3',
      //   roles: ['fd'],
      //   system: 'capi',
      // },
      {
        id: 'capi-fd-wisdom-of-crowds',
        label: 'Wisdom of Crowds',
        href: '/capi/fd/findings/wisdom-of-crowds',
        icon: 'Users',
        roles: ['fd'],
        system: 'capi',
      },
      {
        id: 'capi-fd-approval-ratings',
        label: 'Approval Ratings',
        href: '/capi/fd/findings/approval-ratings',
        icon: 'ThumbsUp',
        roles: ['fd'],
        system: 'capi',
      },
      {
        id: 'capi-fd-preferred-cm',
        label: 'Preferred Leader',
        href: '/capi/fd/findings/preferred-leader',
        icon: 'Users',
        roles: ['fd'],
        system: 'capi',
      },
      {
        id: 'capi-fd-key-issues',
        label: 'Key Issues',
        href: '/capi/fd/findings/key-issues',
        icon: 'AlertCircle',
        roles: ['fd'],
        system: 'capi',
      },
    ],
  },

  // {
  //   id: 'capi-fd-client-comparison',
  //   label: 'Client Comparison',
  //   href: '/capi/fd/client-comparison',
  //   icon: 'BarChart3',
  //   roles: ['fd'],
  //   system: 'capi',
  // },
  {
    id: 'capi-fd-interview-audio',
    label: 'Interview Audio',
    href: '/capi/fd/interview-audio',
    icon: 'Mic',
    roles: ['fd'],
    system: 'capi',
  },
  // {
  //   id: 'capi-back-to-home',
  //   label: 'Back To Home',
  //   href: '/home',
  //   icon: 'Home',
  //   roles: ['fd'],
  //   system: 'capi',
  // },
  {
    id: 'capi-go-to-cati',
    label: 'Go To CATI',
    href: '/cati/fd/telecaller-progress',
    icon: 'MapPin',
    roles: ['fd'],
    system: 'capi',
  },
  // {
  //   id: 'back',
  //   label: 'Back To Menu',
  //   href: '/home',
  //   icon: 'Home',
  //   roles: ['fd'],
  //   system: 'cati',
  // },
  // CAPI Access to Raw Data Menu
  {
    id: 'capi-atrd-capi',
    label: 'CAPI',
    href: '/capi/atrd/capi',
    icon: 'Database',
    roles: ['atrd'],
    system: 'capi',
  },
  {
    id: 'capi-atrd-cati',
    label: 'CATI',
    href: '/capi/atrd/cati',
    icon: 'Phone',
    roles: ['atrd'],
    system: 'capi',
  },
  {
    id: 'capi-atrd-capi-cati',
    label: 'CAPI + CATI',
    href: '/capi/atrd/capi-cati',
    icon: 'Database',
    roles: ['atrd'],
    system: 'capi',
  },

  // CAPI WB Admin Menu
  {
    id: 'capi-wba',
    label: 'WB Admin',
    href: '/capi/wba',
    icon: 'Settings',
    roles: ['wba'],
    system: 'capi',
  },

  // CAPI Normalization Dashboard Menu
  {
    id: 'capi-nd',
    label: 'Normalization Dashboard',
    href: '/capi/nd',
    icon: 'BarChart3',
    roles: ['nd'],
    system: 'capi',
  },

  // PMT Menu (Legacy - keeping for backward compatibility)
  {
    id: 'pmt',
    label: 'PMT',
    href: '/pmt/dashboard',
    icon: 'BarChart3',
    roles: ['pmt'],
    children: [
      {
        id: 'pmt-dashboard',
        label: 'PMT Dashboard',
        href: '/pmt/dashboard',
        icon: 'Home',
        roles: ['pmt'],
      },
      {
        id: 'interview-log',
        label: 'Interview Log',
        href: '/pmt/interview-log',
        icon: 'FileText',
        roles: ['pmt'],
      },
      {
        id: 'demographic-pc',
        label: 'Demographic % (PC)',
        href: '/pmt/demographicpc',
        icon: 'Users',
        roles: ['pmt'],
      },
      {
        id: 'audit-log',
        label: 'Audit Log',
        href: '/pmt/audit',
        icon: 'FileText',
        roles: ['pmt'],
      },
      {
        id: 'cron-requests',
        label: 'Cron Requests',
        href: '/pmt/cron-request',
        icon: 'Clock',
        roles: ['pmt'],
      },
      {
        id: 'broadcasts',
        label: 'Broadcasts',
        href: '/pmt/broadcast',
        icon: 'Bell',
        roles: ['pmt'],
      },
      {
        id: 'broadcasts-log',
        label: 'Broadcasts - Log',
        href: '/pmt/broadcast/logdetail',
        icon: 'FileText',
        roles: ['pmt'],
      },
    ],
  },
  {
    id: 'master',
    label: 'Master',
    href: '/pmt/master',
    icon: 'Database',
    roles: ['pmt'],
    children: [
      {
        id: 'ac-list',
        label: 'AC List',
        href: '/pmt/master-ac',
        icon: 'Users',
        roles: ['pmt'],
      },
      {
        id: 'agency-list',
        label: 'Agency List',
        href: '/pmt/master-agency',
        icon: 'Users',
        roles: ['pmt'],
      },
      {
        id: 'project-setting',
        label: 'Project Setting',
        href: '/pmt/setting',
        icon: 'Settings',
        roles: ['pmt'],
      },
    ],
  },
  {
    id: 'progress-report',
    label: 'Progress Report',
    href: '/pmt/progress',
    icon: 'BarChart3',
    roles: ['pmt'],
  },
  {
    id: 'fail-report',
    label: 'Fail Report',
    href: '/pmt/progress/default/rejectreport',
    icon: 'XCircle',
    roles: ['pmt'],
  },
  {
    id: 'qc-fail-report',
    label: 'QC Fail Report',
    href: '/pmt/progress/qcrejectrepor',
    icon: 'XCircle',
    roles: ['pmt'],
  },
  {
    id: 'gps-map',
    label: 'GPS Map',
    href: '/pmt/progress/gpsmap',
    icon: 'Map',
    roles: ['pmt'],
  },
  {
    id: 'interview-detail',
    label: 'Interview Detail',
    href: '/pmt/progress/interviewdetail',
    icon: 'FileText',
    roles: ['pmt'],
  },
  {
    id: 'master-ps',
    label: 'Master PS',
    href: '/pmt/progress/master-poling-station',
    icon: 'MapPin',
    roles: ['pmt'],
  },
  {
    id: 'demographic-percent',
    label: 'Demographic %',
    href: '/pmt/progress/demographic',
    icon: 'Users',
    roles: ['pmt'],
    children: [
      {
        id: 'gender-wise',
        label: 'Gender Wise',
        href: '/pmt/progress/demographic',
        icon: 'Users',
        roles: ['pmt'],
      },
      {
        id: 'age-wise',
        label: 'Age Wise',
        href: '/pmt/progress/demographic/agewise',
        icon: 'Users',
        roles: ['pmt'],
      },
      {
        id: 'religion-wise',
        label: 'Religion Wise',
        href: '/pmt/progress/demographic/religionwise',
        icon: 'Users',
        roles: ['pmt'],
      },
      {
        id: 'social-category',
        label: 'Social Category',
        href: '/pmt/progress/demographic/socialcategorywise',
        icon: 'Users',
        roles: ['pmt'],
      },
      {
        id: 'caste-wise',
        label: 'Caste Wise',
        href: '/pmt/progress/demographic/castewise',
        icon: 'Users',
        roles: ['pmt'],
      },
    ],
  },

  // Data Manager Menu
  {
    id: 'data-manager-capi',
    label: 'F2F Data',
    href: '/dm/capi',
    icon: 'Database',
    roles: ['data_manager'],
  },
  {
    id: 'data-manager-cati',
    label: 'CATI Data',
    href: '/dm/cati',
    icon: 'Phone',
    roles: ['data_manager'],
  },
  // {
  //   id: 'data-manager-combine',
  //   label: 'Combine Data',
  //   href: '/dm/combine',
  //   icon: 'GitCompare',
  //   roles: ['data_manager'],
  // },

  // ============================================
  // CATI SYSTEM MENUS
  // ============================================

  // CATI Project Progress Monitoring (PPM) Menu
  {
    id: 'cati-ppm-manage-calling',
    label: 'Manage Calling',
    href: '/cati/ppm/manage-calling/tele-caller',
    icon: 'Phone',
    roles: ['ppm'],
    system: 'cati',
    children: [
      {
        id: 'cati-ppm-tele-caller',
        label: 'Tele Caller',
        href: '/cati/ppm/manage-calling/tele-caller',
        icon: 'Phone',
        roles: ['ppm'],
        system: 'cati',
      },
      {
        id: 'cati-ppm-qc-user',
        label: 'QC Users',
        href: '/cati/ppm/manage-calling/qc-user',
        icon: 'CheckCircle',
        roles: ['ppm'],
        system: 'cati',
      },
      // {
      //   id: 'cati-ppm-data-entry-user',
      //   label: 'Data Entry Users',
      //   href: '/cati/ppm/manage-calling/data-entry-user',
      //   icon: 'Edit',
      //   roles: ['ppm'],
      //   system: 'cati',
      // },
    ],
  },
  {
    id: 'cati-ppm-progress',
    label: 'Progress',
    href: '/cati/ppm/progress/telecaller-progress',
    icon: 'BarChart3',
    roles: ['ppm'],
    system: 'cati',
    children: [
      {
        id: 'cati-ppm-telecaller-daily-progress',
        label: 'Telecaller Progress',
        href: '/cati/ppm/progress/telecaller-progress',
        icon: 'TrendingUp',
        roles: ['ppm'],
        system: 'cati',
      },
      {
        id: 'cati-ppm-telecaller-daily-call-detail',
        label: 'Telecaller Daily Call Detail',
        href: '/cati/ppm/progress/telecaller-daily-call-detail',
        icon: 'FileText',
        roles: ['ppm'],
        system: 'cati',
      },
    ],
  },
  // {
  //   id: 'cati-ppm-ac-progress',
  //   label: 'AC Progress',
  //   href: '/cati/ppm/ac-progress/overall-ac-progress',
  //   icon: 'MapPin',
  //   roles: ['ppm'],
  //   system: 'cati',
  //   children: [
  //     {
  //       id: 'cati-ppm-overall-ac-progress',
  //       label: 'Overall AC Progress',
  //       href: '/cati/ppm/ac-progress/overall-ac-progress',
  //       icon: 'BarChart3',
  //       roles: ['ppm'],
  //       system: 'cati',
  //     },
  //     {
  //       id: 'cati-ppm-ac-progress',
  //       label: 'AC Progress',
  //       href: '/cati/ppm/ac-progress/ac-progress',
  //       icon: 'BarChart3',
  //       roles: ['ppm'],
  //       system: 'cati',
  //     },
  //   ],
  // },
  {
    id: 'cati-ppm-team-registration',
    label: 'Team Registration',
    href: '/cati/ppm/team-registration',
    icon: 'Users',
    roles: ['ppm'],
    system: 'cati',
  },
  {
    id: 'cati-ppm-performance',
    label: 'Performance',
    href: '/cati/ppm/performance',
    icon: 'BarChart3',
    roles: ['ppm'],
    system: 'cati',
  },
  {
    id: 'cati-ppm-quota-monitoring',
    label: 'Quota Monitoring',
    href: '/cati/ppm/quota-monitoring',
    icon: 'Users',
    roles: ['ppm'],
    system: 'cati',
  },
  {
    id: 'cati-ppm-masterdata',
    label: 'Master Data',
    href: '/cati/ppm/master-data',
    icon: 'BarChart3',
    roles: ['ppm'],
    system: 'cati',
    children: [
      {
        id: 'cati-ppm-call-outcome-tracker',
        label: 'Call Outcome Tracker',
        href: '/cati/ppm/masterdata/call-outcome-tracker',
        icon: 'TrendingUp',
        roles: ['ppm'],
        system: 'cati',
      },
      {
        id: 'cati-ppm-master-data',
        label: 'Master Data',
        href: '/cati/ppm/masterdata/master-data',
        icon: 'FileText',
        roles: ['ppm'],
        system: 'cati',
      },
    ],
  },
  

// end ppm menu
  //  ===========================================Team (PPMT) Menu
  {
    id: 'cati-ppmt-progress',
    label: 'Progress',
    href: '/cati/ppmt/progress/telecaller-progress',
    icon: 'BarChart3',
    roles: ['group'],
    system: 'cati',
    children: [
      {
        id: 'cati-ppmt-telecaller-daily-progress',
        label: 'Telecaller Progress',
        href: '/cati/ppmt/progress/telecaller-progress',
        icon: 'TrendingUp',
        roles: ['group'],
        system: 'cati',
      },
      {
        id: 'cati-ppmt-telecaller-daily-call-detail',
        label: 'Telecaller Daily Call Detail',
        href: '/cati/ppmt/progress/telecaller-daily-call-detail',
        icon: 'FileText',
        roles: ['group'],
        system: 'cati',
      },
    ],
  },

  // ===========================================
  // ===========================================
  // ===========================================


  // CATI Client Dashboard (CD) Menu
  {
    id: 'cati-fd-telecaller-performance',
    label: 'Performance',
    href: '/cati/fd/performance',
    icon: 'BarChart3',
    roles: ['fd'],
    system: 'cati',
  },
  {
    id: 'cati-fd-quota-monitoring',
    label: 'Quota Monitoring',
    href: '/cati/fd/quota-monitoring',
    icon: 'Users',
    roles: ['fd'],
    system: 'cati',
  },
  // fd menu end
  // CATI Start Survey (SS) Menu
  {
    id: 'cati-ss-start-form-filling',
    label: 'Authentication',
    href: '/cati/ss/start-form-filling',
    icon: 'Securitysss',
    roles: ['ss'],
    system: 'cati',
  },
  {
    id: 'cati-ss-fill-form',
    label: 'Start Form Filling',
    href: '/cati/ss/new-call',
    icon: 'Edit',
    roles: ['ss'],
    system: 'cati',
    dynamic: true, // This will be dynamically set based on teleform user data
  },
  {
    id: 'cati-ss-qc',
    label: 'Start QC',
    href: '/cati/ss/qc-call',
    icon: 'CheckCircle',
    roles: ['ss'],
    system: 'cati',
    dynamic: true, // This will be dynamically set based on teleform user data
  },

  // Data Entry Role Menu (Simple like SS role)
  {
    id: 'cati-data-entry-auth',
    label: 'Authentication',
    href: '/cati/data-entry',
    icon: 'Shield',
    roles: ['data_entry'],
    system: 'cati',
  },
  {
    id: 'cati-data-entry',
    label: 'Start QC',
    href: '/cati/ss/data-entry-list',
    icon: 'CheckCircle',
    roles: ['data_entry'],
    system: 'cati',
    dynamic: true, // This will be dynamically set based on data entry user data
  },

];

export const getMenuByRole = (role: string, userSystem?: 'capi' | 'cati'): MenuItem[] => {
  return menuData.filter(item => {
    const hasRole = item.roles.includes(role) || item.roles.includes('admin');

    // If item has no system specified (common menus), show for all users
    if (!item.system) return hasRole;

    // If user has no system (admin roles), show common menus only
    if (!userSystem) return hasRole && !item.system;

    // Match both role and system
    return hasRole && item.system === userSystem;
  }).map(item => ({
    ...item,
    children: item.children ? item.children.filter(child => {
      const childHasRole = child.roles.includes(role) || child.roles.includes('admin');

      // If child has no system specified, show for all users
      if (!child.system) return childHasRole;

      // If user has no system, show common menus only
      if (!userSystem) return childHasRole && !child.system;

      // Match both role and system
      return childHasRole && child.system === userSystem;
    }) : undefined,
  }));
};
