import { MenuItem } from '@/types';

export const menuData: MenuItem[] = [
  {
    id: 'dashboard',
    label: 'Dashboard',
    href: '/dashboard',
    icon: 'Home',
    roles: ['super_admin', 'admin', 'pmt', 'qc', 'quality-analyst', 'start-qc', 'data-quality'],
  },
  {
    id: 'user-management',
    label: 'User Management',
    href: '/dashboard/user-management',
    icon: 'UserCog',
    roles: ['super_admin'],
  },
  {
    id: 'analysis',
    label: 'Analysis',
    href: '/dashboard/analysis',
    icon: 'BarChart3',
    roles: ['super_admin', 'admin', 'pmt', 'qc', 'quality-analyst'],
    children: [
      {
        id: 'vote-share',
        label: 'Vote Share Analysis',
        href: '/dashboard/analysis/vote-share',
        icon: 'BarChart3',
        roles: ['super_admin', 'admin', 'pmt', 'qc', 'quality-analyst'],
      },
      {
        id: 'progress-overview',
        label: 'Progress Overview',
        href: '/dashboard/analysis/progress',
        icon: 'CheckCircle',
        roles: ['super_admin', 'admin', 'pmt', 'qc', 'quality-analyst'],
      },
    ],
  },
  {
    id: 'pmt',
    label: 'PMT System',
    href: '/dashboard/pmt',
    icon: 'Users',
    roles: ['super_admin', 'admin', 'pmt'],
    children: [
      {
        id: 'agency-list',
        label: 'Agency List',
        href: '/dashboard/pmt/agencies',
        icon: 'Users',
        roles: ['super_admin', 'admin', 'pmt'],
      },
      {
        id: 'audit-log',
        label: 'Audit Log',
        href: '/dashboard/pmt/audit',
        icon: 'FileText',
        roles: ['super_admin', 'admin', 'pmt'],
      },
      {
        id: 'cron-requests',
        label: 'Cron Requests',
        href: '/dashboard/pmt/cron',
        icon: 'Calendar',
        roles: ['super_admin', 'admin', 'pmt'],
      },
      {
        id: 'interview-log',
        label: 'Interview Log',
        href: '/dashboard/pmt/interviews',
        icon: 'FileText',
        roles: ['super_admin', 'admin', 'pmt'],
      },
      {
        id: 'settings',
        label: 'Settings',
        href: '/dashboard/pmt/settings',
        icon: 'Settings',
        roles: ['super_admin', 'admin', 'pmt'],
        children: [
          {
            id: 'project-info',
            label: 'Project Info',
            href: '/dashboard/pmt/settings/project-info',
            icon: 'Settings',
            roles: ['super_admin', 'admin', 'pmt'],
          },
          {
            id: 'project-theme',
            label: 'Project Theme',
            href: '/dashboard/pmt/settings/theme',
            icon: 'Settings',
            roles: ['super_admin', 'admin', 'pmt'],
          },
          {
            id: 'question-types',
            label: 'Question Types',
            href: '/dashboard/pmt/settings/question-types',
            icon: 'Settings',
            roles: ['super_admin', 'admin', 'pmt'],
          },
          {
            id: 'survey-dates',
            label: 'Survey Dates',
            href: '/dashboard/pmt/settings/survey-dates',
            icon: 'Calendar',
            roles: ['super_admin', 'admin', 'pmt'],
          },
          {
            id: 'sample-size',
            label: 'Sample Size',
            href: '/dashboard/pmt/settings/sample-size',
            icon: 'Users',
            roles: ['super_admin', 'admin', 'pmt'],
          },
        ],
      },
      {
        id: 'demographics',
        label: 'Demographics',
        href: '/dashboard/pmt/demographics',
        icon: 'Users',
        roles: ['super_admin', 'admin', 'pmt'],
      },
      {
        id: 'broadcasts',
        label: 'Broadcasts',
        href: '/dashboard/pmt/broadcasts',
        icon: 'Bell',
        roles: ['super_admin', 'admin', 'pmt'],
      },
      {
        id: 'master-ac-list',
        label: 'Master AC List',
        href: '/dashboard/pmt/master-ac',
        icon: 'Users',
        roles: ['super_admin', 'admin', 'pmt'],
      },
    ],
  },
  {
    id: 'qc',
    label: 'QC Management',
    href: '/dashboard/qc',
    icon: 'Shield',
    roles: ['super_admin', 'admin', 'qc'],
    children: [
      {
        id: 'fieldwork-progress',
        label: 'Fieldwork Progress',
        href: '/dashboard/qc/fieldwork',
        icon: 'CheckCircle',
        roles: ['super_admin', 'admin', 'qc'],
      },
      {
        id: 'gps-map',
        label: 'GPS Map',
        href: '/dashboard/qc/gps',
        icon: 'MapPin',
        roles: ['super_admin', 'admin', 'qc'],
      },
      {
        id: 'progress-report',
        label: 'Progress Report',
        href: '/dashboard/qc/progress-report',
        icon: 'FileText',
        roles: ['super_admin', 'admin', 'qc'],
      },
      {
        id: 'rejection-report',
        label: 'Rejection Report',
        href: '/dashboard/qc/rejection-report',
        icon: 'AlertTriangle',
        roles: ['super_admin', 'admin', 'qc'],
      },
    ],
  },
  {
    id: 'quality-analyst',
    label: 'Quality Analyst',
    href: '/dashboard/quality-analyst',
    icon: 'UserCheck',
    roles: ['super_admin', 'admin', 'quality-analyst'],
    children: [
      {
        id: 'demographic-analysis',
        label: 'Demographic Analysis',
        href: '/dashboard/quality-analyst/demographics',
        icon: 'Users',
        roles: ['super_admin', 'admin', 'quality-analyst'],
        children: [
          {
            id: 'age-wise',
            label: 'Age Wise',
            href: '/dashboard/quality-analyst/demographics/age',
            icon: 'Users',
            roles: ['super_admin', 'admin', 'quality-analyst'],
          },
          {
            id: 'caste-wise',
            label: 'Caste Wise',
            href: '/dashboard/quality-analyst/demographics/caste',
            icon: 'Users',
            roles: ['super_admin', 'admin', 'quality-analyst'],
          },
          {
            id: 'gender-wise',
            label: 'Gender Wise',
            href: '/dashboard/quality-analyst/demographics/gender',
            icon: 'Users',
            roles: ['super_admin', 'admin', 'quality-analyst'],
          },
          {
            id: 'locality-wise',
            label: 'Locality Wise',
            href: '/dashboard/quality-analyst/demographics/locality',
            icon: 'MapPin',
            roles: ['super_admin', 'admin', 'quality-analyst'],
          },
          {
            id: 'religion-wise',
            label: 'Religion Wise',
            href: '/dashboard/quality-analyst/demographics/religion',
            icon: 'Users',
            roles: ['super_admin', 'admin', 'quality-analyst'],
          },
          {
            id: 'social-category',
            label: 'Social Category',
            href: '/dashboard/quality-analyst/demographics/social-category',
            icon: 'Users',
            roles: ['super_admin', 'admin', 'quality-analyst'],
          },
        ],
      },
      {
        id: 'fieldwork-progress',
        label: 'Fieldwork Progress',
        href: '/dashboard/quality-analyst/fieldwork',
        icon: 'CheckCircle',
        roles: ['super_admin', 'admin', 'quality-analyst'],
      },
      {
        id: 'gps-map',
        label: 'GPS Map',
        href: '/dashboard/quality-analyst/gps',
        icon: 'MapPin',
        roles: ['super_admin', 'admin', 'quality-analyst'],
      },
      {
        id: 'progress-report',
        label: 'Progress Report',
        href: '/dashboard/quality-analyst/progress-report',
        icon: 'FileText',
        roles: ['super_admin', 'admin', 'quality-analyst'],
      },
      {
        id: 'rejection-report',
        label: 'Rejection Report',
        href: '/dashboard/quality-analyst/rejection-report',
        icon: 'AlertTriangle',
        roles: ['super_admin', 'admin', 'quality-analyst'],
      },
    ],
  },
  {
    id: 'start-qc',
    label: 'Start QC',
    href: '/dashboard/start-qc',
    icon: 'Play',
    roles: ['super_admin', 'admin', 'start-qc'],
    children: [
      {
        id: 'qc-workflow',
        label: 'QC Workflow',
        href: '/dashboard/start-qc/workflow',
        icon: 'Play',
        roles: ['super_admin', 'admin', 'start-qc'],
      },
    ],
  },
  {
    id: 'data-quality',
    label: 'Data Quality',
    href: '/dashboard/data-quality',
    icon: 'Database',
    roles: ['super_admin', 'admin', 'data-quality'],
    children: [
      {
        id: 'data-validation',
        label: 'Data Validation',
        href: '/dashboard/data-quality/validation',
        icon: 'CheckCircle',
        roles: ['super_admin', 'admin', 'data-quality'],
      },
      {
        id: 'quality-metrics',
        label: 'Quality Metrics',
        href: '/dashboard/data-quality/metrics',
        icon: 'BarChart3',
        roles: ['super_admin', 'admin', 'data-quality'],
      },
    ],
  },
  {
    id: 'components',
    label: 'Components',
    href: '/dashboard/components',
    icon: 'Sliders',
    roles: ['super_admin', 'admin', 'pmt', 'qc', 'quality-analyst', 'start-qc', 'data-quality'],
    children: [
      {
        id: 'select-demo',
        label: 'Select Components',
        href: '/dashboard/components/select-demo',
        icon: 'CheckCircle',
        roles: ['super_admin', 'admin', 'pmt', 'qc', 'quality-analyst', 'start-qc', 'data-quality'],
      },
      {
        id: 'form-validation-demo',
        label: 'Form Validation',
        href: '/dashboard/components/form-validation-demo',
        icon: 'FileText',
        roles: ['super_admin', 'admin', 'pmt', 'qc', 'quality-analyst', 'start-qc', 'data-quality'],
      },
      {
        id: 'form-builder-demo',
        label: 'Form Builder',
        href: '/dashboard/components/form-builder-demo',
        icon: 'Settings',
        roles: ['super_admin', 'admin', 'pmt', 'qc', 'quality-analyst', 'start-qc', 'data-quality'],
      },
      {
        id: 'modal-demo',
        label: 'Modal Components',
        href: '/dashboard/components/modal-demo',
        icon: 'FileText',
        roles: ['super_admin', 'admin', 'pmt', 'qc', 'quality-analyst', 'start-qc', 'data-quality'],
      },
      {
        id: 'form-components-demo',
        label: 'Form Components',
        href: '/dashboard/components/form-components-demo',
        icon: 'Settings',
        roles: ['super_admin', 'admin', 'pmt', 'qc', 'quality-analyst', 'start-qc', 'data-quality'],
      },
      {
        id: 'ui-components-demo',
        label: 'UI Components',
        href: '/dashboard/components/ui-components-demo',
        icon: 'Sliders',
        roles: ['super_admin', 'admin', 'pmt', 'qc', 'quality-analyst', 'start-qc', 'data-quality'],
      },
      {
        id: 'medium-components-demo',
        label: 'Medium Components',
        href: '/dashboard/components/medium-components-demo',
        icon: 'BarChart3',
        roles: ['super_admin', 'admin', 'pmt', 'qc', 'quality-analyst', 'start-qc', 'data-quality'],
      },
          {
            id: 'utility-components-demo',
            label: 'Utility Components',
            href: '/dashboard/components/utility-components-demo',
            icon: 'Settings',
            roles: ['super_admin', 'admin', 'pmt', 'qc', 'quality-analyst', 'start-qc', 'data-quality'],
          },
          {
            id: 'advanced-components-demo',
            label: 'Advanced Components',
            href: '/dashboard/components/advanced-components-demo',
            icon: 'Settings',
            roles: ['super_admin', 'admin', 'pmt', 'qc', 'quality-analyst', 'start-qc', 'data-quality'],
          },
    ],
  },
];

export const getMenuByRole = (role: string): MenuItem[] => {
  return menuData.filter(item => 
    item.roles.includes(role) || item.roles.includes('admin')
  ).map(item => ({
    ...item,
    children: item.children ? item.children.filter(child => 
      child.roles.includes(role) || child.roles.includes('admin')
    ) : undefined,
  }));
};
